name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # 每30分钟检查一次更新

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main       # 假设主分支为main
          fetch-depth: 0  # 获取所有历史

      - name: Sync fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "danny-avila/LibreChat"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.MY_PERSONAL_TOKEN }}
